### ISSUE TITLE
Mejorar Navbar en responsive

### ISSUE THREAD

**Issue by juanpabloe** [hackerschoolmty/website#1]
Así se ve ahora:
![screen shot 2017-10-18 at 11 24 59 am](https://user-images.githubusercontent.com/542209/31730300-2471c22c-b3f7-11e7-9c4b-debb3c16e185.png)

**Comment by juanpabloe** [comment]
Cuando el menú está abierto se pierde con el contenido. Quizá necesita un background
![screen shot 2017-10-18 at 11 30 37 am](https://user-images.githubusercontent.com/542209/31730553-e3deab2a-b3f7-11e7-8c27-1a61caa2d1cb.png)

**Comment by gmarinozzi** [comment]
Preferís que le ponga un fondo de color? ahora tiene un gradiente, pero es muy transparente y no hay suficiente contraste con el fondo

**Comment by juanpabloe** [comment]
Podría ser algo que facilite que sea más legible.
